name: CI
on: [push, pull_request]

jobs:
  ci:
    name: Build, test, lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58
      - name: Install dependencies
        run: go get .
      - name: Build
        run: make build
      - name: Test
        run: make test
      - name: Lint
        run: make lint
